name: "Run RSFC"
on:
  workflow_call:
    inputs:
      repo_url:
        description: 'Repository URL to analyze'
        required: true
        type: string
    secrets:
      RSFC_TOKEN:
        required: false

jobs:
  run-rsfc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install RSFC
        run: pip install rsfc
      - name: Configure Somef
        run: somef configure -a
      - name: Download NLTK data (wordnet)
        run: |
          python -m nltk.downloader wordnet
          python -m nltk.downloader omw-1.4
      - name: Create outputs directory
        # run: mkdir -p outputs
        run: mkdir -p rsfc_output
      - name: Run RSFC
        run: |
          if [ -z "${{ secrets.RSFC_TOKEN }}" ]; then
            echo "Running RSFC on public repo"
            rsfc --repo ${{ inputs.repo_url }}
          else
            echo "Running RSFC on private repo with token"
            rsfc --repo ${{ inputs.repo_url }} --token ${{ secrets.RSFC_TOKEN }} 
          fi
      - name: Upload RSFC report
        uses: actions/upload-artifact@v4
        with:
          name: rsfc-report
          path: rsfc_output

      - name: Show RSFC report location
        run: |
          echo "RSFC assessment completed."
          echo "Report available here:"
          echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Get job ID
        id: get_job
        uses: actions/github-script@v7
        with:
          script: |
            const jobs = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            })

            const job = jobs.data.jobs.find(j => j.name === process.env.GITHUB_JOB)
            core.setOutput("job_id", job.id)
            
      - name: Create neutral check
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request
            const jobId = "${{ steps.get_job.outputs.job_id }}"
            const url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/job/${jobId}`

            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "RSFC assessment",
              head_sha: pr.head.sha,
              status: "completed",
              conclusion: "neutral",
              output: {
                title: "RSFC report",
                summary: `:\n${url}`
              }
            })
